name: BenHunt
favicon: null
layout_spectrum: 0.04217129782773554
typography_spectrum: 0.24587359139695764
title: 'Ben Hunt, Marketing Strategist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2624980-40
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050908'
    - '#bda28d'
    - '#646055'
    - '#5f0b12'
  brandStrength: 0.25
  lightness: 0.1774653505999595
  saturation: 0.2150110227521509
  rhythmicContrast: 0.39876856096088886
purpose: []
