name: BenHunt
favicon: null
layout_spectrum: 0.04217129782773554
typography_spectrum: 0.24587359139695764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9337299710605294
  lightness: 0.1774653505999595
  saturation: 0.2150110227521509
  rhythmicContrast: 0.39876856096088886
purpose: []
