name: BenHunt
favicon: null
layout_spectrum: 0.51336
typography_spectrum: 0.87024
title: 'Ben Hunt, Marketing Strategist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2624980-40
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121f05'
    - '#f0ece3'
    - '#77c0fa'
    - '#4e5f13'
    - '#5b738c'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
