name: BenHunt
favicon: null
layout_spectrum: 0.04217129782773554
typography_spectrum: 0.87692
title: 'Ben Hunt, Marketing Strategist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2624980-40
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050908'
    - '#bda28d'
    - '#646055'
    - '#5f0b12'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.2150110227521509
  rhythmicContrast: 0.25
purpose: []
